-- Auto-incrementing per-booking sequence number, surfaced as "BKNG-00001"
-- (lib/booking-ref) in the UI and in every customer/driver message so the
-- reference can be quoted and traced back. Postgres assigns values to existing
-- rows when the identity column is added; new rows get the next value.
ALTER TABLE "bookings" ADD COLUMN "seq" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;
